[package]
name = "cargo-doc-md"
version = "0.7.2"
edition = "2024"
authors = ["Claude (Anthropic AI) <noreply@anthropic.com>"]
license = "MIT OR Apache-2.0"
description = "Cargo subcommand to generate markdown documentation for Rust crates and dependencies"
readme = "README.md"
repository = "https://github.com/Crazytieguy/rustdoc-json-to-markdown"
homepage = "https://github.com/Crazytieguy/rustdoc-json-to-markdown"
keywords = ["cargo-subcommand", "markdown", "documentation", "rustdoc", "cargo"]
categories = ["command-line-utilities", "development-tools"]
rust-version = "1.85"

[[bin]]
name = "cargo-doc-md"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
serde_json = "1.0.145"
rustdoc-types = { version = "0.56", features = ["rustc-hash"] }
